name: Build Sketches
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install libraries
      with:
        libraries: libraries
    - name: Build all sketches
      uses: Legion2/arduino-builder-action@v2.0.0
      with:
        board: "arduino:avr:uno"
        sketchDirectory: sketch
